# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xmit < Formula
  desc "Launch static websites on xmit.co"
  homepage "https://xmit.co/"
  version "0.5.1"

  on_macos do
    on_intel do
      url "https://github.com/xmit-co/xmit/releases/download/v0.5.1/xmit_0.5.1_darwin_amd64.zip"
      sha256 "164cee6eeff1fb253f39e4fcd68ee8e5272cd3f7e26d2bcb5dafea11f160fa1e"

      def install
        bin.install "xmit"
      end
    end
    on_arm do
      url "https://github.com/xmit-co/xmit/releases/download/v0.5.1/xmit_0.5.1_darwin_arm64.zip"
      sha256 "153f8cd1dd2b3945c86cfd76f3447bdebdd7d74bc0f8a60fda42a880f3b73ce7"

      def install
        bin.install "xmit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xmit-co/xmit/releases/download/v0.5.1/xmit_0.5.1_linux_amd64.zip"
        sha256 "d1802c07a863bb4e8790d8bbf49d4e65087eaebfe7036d87a1a5ebec4d1cb96b"

        def install
          bin.install "xmit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xmit-co/xmit/releases/download/v0.5.1/xmit_0.5.1_linux_arm64.zip"
        sha256 "8f8bf85d1780dae8dd6d04ef816d74e0936fda2593353a88ee94a2e8a81251a8"

        def install
          bin.install "xmit"
        end
      end
    end
  end
end
