# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xmit < Formula
  desc "Launch static websites on xmit.co"
  homepage "https://xmit.co/"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/xmit-co/xmit/releases/download/v0.3.0/xmit_0.3.0_darwin_amd64.zip"
      sha256 "a6aac49b127fae06e243a995d87085a7a94b4583447a57295fe76530fd935bc0"

      def install
        bin.install "xmit"
      end
    end
    on_arm do
      url "https://github.com/xmit-co/xmit/releases/download/v0.3.0/xmit_0.3.0_darwin_arm64.zip"
      sha256 "edc59f0488487ec23f1d4ba2fcacd7533f508ea01aedc783c28eb235cd8d5c01"

      def install
        bin.install "xmit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xmit-co/xmit/releases/download/v0.3.0/xmit_0.3.0_linux_amd64.zip"
        sha256 "e272536232742c36ae1e8e5be0a8728a4b710c21d075c94d8f9ca52ceea0f02d"

        def install
          bin.install "xmit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/xmit-co/xmit/releases/download/v0.3.0/xmit_0.3.0_linux_arm64.zip"
        sha256 "74161fcfe00b825a124c381414ee34d8c3c53a5c2fb99e8a60298786bb851e54"

        def install
          bin.install "xmit"
        end
      end
    end
  end
end
